name: tone_track
description: "A diary application that analyzes entries based on sentiment analysis, helping users track and understand their emotional states over time."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  animated_text_kit: ^4.2.0
  path: ^1.8.0
  path_provider: ^2.0.0
  sqflite: ^2.4.1
  dio: ^5.7.0
  provider: ^6.1.2
  cupertino_icons: ^1.0.8
  intl: ^0.20.0
  lens_button:
    git:
      url: https://github.com/Alpaca00/lens_button.git
      ref: tech/update-button

dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  mockito: ^5.4.4
  flutter_lints: ^4.0.0
  test: ^1.22.0
  allure_report: ^1.0.0
  test_reporter: ^1.0.0
#  dart_dot_reporter:
#    git:
#      url: https://github.com/kwiatek91/dart_dot_reporter.git
#      ref: dart_update_2

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/logo.png"

flutter:
  assets:
    - assets/images/background.jpg
    - assets/icons/logo.png
  uses-material-design: true
